M48
; DRILL file KiCad 10.0.1 date 2026-06-02T21:22:15
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-02T21:22:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X6.5791Y-5.5
X6.8067Y-5.5
T2
X7.1223Y-5.5394
M30
