M48
; DRILL file KiCad 10.0.1 date 2026-06-18T15:04:04
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-18T15:04:04+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X6.2394Y-5.7114
X6.4669Y-5.7114
T2
X10.2512Y-4.4114
M30
