M48
; DRILL file KiCad 10.0.1 date 2026-06-16T20:08:50
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-16T20:08:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X8.9748Y-2.7689
T2
X8.7626Y-5.7008
X8.9902Y-5.7008
T3
X8.0837Y-4.5676
X8.0837Y-4.6857
M30
