M48
; DRILL file KiCad 10.0.1 date 2026-06-05T15:07:20
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-06-05T15:07:20+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X6.1157Y-3.9354
X6.1157Y-4.163
T2
X5.9843Y-3.565
M30
